## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [11]:
a=np.random.randint(0,10,10)
print(a) 
a[(a<8) & (a>3)]*=-1       
print(a)

[3 3 1 4 6 3 3 8 1 6]
[ 3  3  1 -4 -6  3  3  8  1 -6]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
a=np.random.randint(1,20,10)
print(a) 
a[np.argmax(a)]=0
print(a)

[11 18 15  8 13  5 14 19 18  5]
[11 18 15  8 13  5 14  0 18  5]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [203]:
a = np.random.randint(1, 11, size=(4, 3))
print(a)
b=np.indices(map(len, a))
b=b.reshape(len(a),-1).T
#matrix of all variants
for i in range(len(a)):
        b[:,i]=a[i][b[:,i]]
print(b)


[[ 4 10  8]
 [ 3  7  3]
 [ 6  9  1]
 [ 6  9  1]]
[[ 4  3  6  6]
 [ 4  3  6  9]
 [ 4  3  6  1]
 [ 4  3  9  6]
 [ 4  3  9  9]
 [ 4  3  9  1]
 [ 4  3  1  6]
 [ 4  3  1  9]
 [ 4  3  1  1]
 [ 4  7  6  6]
 [ 4  7  6  9]
 [ 4  7  6  1]
 [ 4  7  9  6]
 [ 4  7  9  9]
 [ 4  7  9  1]
 [ 4  7  1  6]
 [ 4  7  1  9]
 [ 4  7  1  1]
 [ 4  3  6  6]
 [ 4  3  6  9]
 [ 4  3  6  1]
 [ 4  3  9  6]
 [ 4  3  9  9]
 [ 4  3  9  1]
 [ 4  3  1  6]
 [ 4  3  1  9]
 [ 4  3  1  1]
 [10  3  6  6]
 [10  3  6  9]
 [10  3  6  1]
 [10  3  9  6]
 [10  3  9  9]
 [10  3  9  1]
 [10  3  1  6]
 [10  3  1  9]
 [10  3  1  1]
 [10  7  6  6]
 [10  7  6  9]
 [10  7  6  1]
 [10  7  9  6]
 [10  7  9  9]
 [10  7  9  1]
 [10  7  1  6]
 [10  7  1  9]
 [10  7  1  1]
 [10  3  6  6]
 [10  3  6  9]
 [10  3  6  1]
 [10  3  9  6]
 [10  3  9  9]
 [10  3  9  1]
 [10  3  1  6]
 [10  3  1  9]
 [10  3  1  1]
 [ 8  3  6  6]
 [ 8  3  6  9]
 [ 8  3  6  1]
 [ 8  3  9  6]
 [ 8  3  9  9]
 [ 8  3  9  1]
 [ 8  3  1  6]
 [ 8  3  1  9]
 [ 8  3  1  1]
 [ 8  

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [12]:
a= np.random.randint(1,10,(10,3))
b=np.random.randint(1,10,(2,2))
print (a,b)
for i in range(len(a)):
    if ((b[0][0] in a[i] or b[0][1] in a[i]) and(b[1][0] in a[i] or b[1][1] in a[i])):
        print (i)
        

[[2 9 6]
 [6 3 8]
 [3 8 3]
 [9 2 1]
 [8 6 8]
 [3 9 5]
 [9 5 3]
 [5 7 1]
 [9 4 4]
 [3 3 3]] [[7 6]
 [5 6]]
0
1
4
7


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [116]:
a = np.random.randint(1, 3, size=(10, 3))
print(a)
b=np.array([[]])
b = np.random.randint(1, 3,10)
print(a[:,0:-1])
unique=np.all(a[:,1:] == a[:,0:-1],axis=1)
b=a[~unique]
print(b)

[[1 1 2]
 [2 1 1]
 [1 1 1]
 [1 1 1]
 [1 2 2]
 [1 1 1]
 [1 2 1]
 [2 2 1]
 [2 1 2]
 [2 1 1]]
[[1 1]
 [2 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [2 2]
 [2 1]
 [2 1]]
[[1 1 2]
 [2 1 1]
 [1 2 2]
 [1 2 1]
 [2 2 1]
 [2 1 2]
 [2 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [13]:
a = np.random.randint(1, 3, size=(3, 3))
b=np.array([])
print(a)
for i in a:
    b=np.append(b,np.array2string(i))
unique, index =np.unique(b,return_index=True)
print(a[index])

[[2 1 1]
 [2 2 2]
 [2 2 2]]
[[2 1 1]
 [2 2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [70]:
X = np.random.randint(0, 3, size=(4, 3))
print(X)
X=np.diagonal(X)
print(np.prod(X[X>0]))

Y = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(Y)
prod=1
for i in range(min(len(Y[0]),len(Y))):
    if(Y[i][i]!=0):
        prod*=Y[i][i]
print (prod)

[[2 0 0]
 [0 2 2]
 [1 0 0]
 [1 2 0]]
4
[[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [101]:
X=[1,2,4,2]
Y=[4,2,1]
print(set(X)==set(Y))
X_ = np.random.randint(1,5,3)
Y_ = np.random.randint(1,5,4)
print(X_,Y_)
print (np.array_equal(np.unique(X_),np.unique(Y_)))

True
[2 4 3] [2 3 3 4]
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [130]:
X=[100, 0, 0, 3, 0, 0, 2, 7, 0]
max_element=0
for i in range(len(X)-1):
    if(X[i]==0 and X[i+1]>max_element):
            max_element=X[i+1]
print(max_element)

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 9])
ind=(np.where(x==0)[0])+1
x=np.append(x,0)
print(np.max(x[ind]))


3
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [119]:
X=[1,1,1, 2,2, 5, 3, 3, 3, 5]
temp=X[0]
count=1
first_arr=[]
second_arr=[]
for i in range(1,len(X)):
    if X[i]!=temp:
        first_arr.append(temp)
        second_arr.append(count)
        temp=X[i]
        count=1
    else:
        count+=1
first_arr.append(temp)
second_arr.append(count)

print((first_arr,second_arr))
x=np.array([1,1,1, 2,2, 5, 3, 3, 3, 5])
y=np.diff(x)
z=np.append(np.nonzero(y)[0],len(x)-1)
arr1=x[z]
z=np.insert(z, 0,-1, axis=0)
arr2=np.diff(z)
print((arr1,arr2))

([1, 2, 5, 3, 5], [3, 2, 1, 3, 1])
(array([1, 2, 5, 3, 5]), array([3, 2, 1, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [5]:
import scipy.spatial
from datetime import datetime
def matrix_(A,B):
    P = np.add.outer(np.sum(A**2,axis=1), np.sum(B**2, axis=1))
    N = A@B.T
    dists = np.sqrt(P - 2*N)
    return dists

def distance(x,y):
    return ((x[0]-y[0])**2+(x[1]-y[1])**2)**0.5
def matrix(A,B):
    result=[]
    for i in range(len(A)):
        row=[]
        for j in range(len(B)):
            row.append(distance(A[i],B[j]))
        result.append(row)
    return result

coords = np.array([(35.0456, -85.2672),
          (35.1174, -89.9711),
          (35.9728, -83.9422),
          (36.1667, -86.7833)])

start_time = datetime.now()
print(scipy.spatial.distance.cdist(coords, coords, 'euclidean'))
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

start_time = datetime.now()
print(matrix_(coords,coords))
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

start_time = datetime.now()
print(matrix(coords,coords))
end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))



[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
Duration: 0:00:00.000484
[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
Duration: 0:00:00.000607
[[0.0, 4.704447943170383, 1.6171965990565296, 1.8855833102782755], [4.704447943170383, 0.0, 6.089281104531148, 3.3560541309698886], [1.6171965990565296, 6.089281104531148, 0.0, 2.8477089774062208], [1.8855833102782755, 3.3560541309698886, 2.8477089774062208, 0.0]]
Duration: 0:00:00.000106


# функция из скайпай получилась самая медленная

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [3]:
calorie_stats = np.loadtxt("data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [24]:
average_calories=np.mean(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [22]:
calorie_stats=np.sort(calorie_stats)
calorie_stats

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [4]:
median_calories=np.median(calorie_stats)# your code
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [238]:
nth_percentile=np.percentile(calorie_stats,4)
nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [242]:
more_calories=len(calorie_stats[calorie_stats>60])/len(calorie_stats)
more_calories*100

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [243]:
calorie_std=np.std(calorie_stats)
calorie_std

19.35718533390827

# так как стандартное отклонение имеет не очень большое значение, это значит что значения в выборке приблизительно равны среднему, которое равно около 100 калорий

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

# становится понятно, что СrunchieMunchies  имеет меньше калорий чем большинство злаков на рынке. Благодаря этим данным компания может показать, что её хлопья будут полезнее чем у конкурентов.